//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroHospitalario
    {

        public int idCentroHospitalario { get; set; }
        public string nombre { get; set; }
        public int capacidad { get; set; }
        public int capacidadUci { get; set; }
        public string contacto { get; set; }
        public string director { get; set; }
        public int idUbicacion { get; set; }

    }
}
