//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Centro_Hospitalario
    {
        public Centro_Hospitalario()
        {
            this.Pacientes = new HashSet<Paciente>();
        }
    
        public int Id_Centro_Hospitalario { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<int> Capacidad_UCI { get; set; }
        public string Director { get; set; }
        public string Contacto { get; set; }
        public int Id_Ubicacion { get; set; }
    
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual ICollection<Paciente> Pacientes { get; set; }
    }
}
