//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int Id_Contacto { get; set; }
        public string Correo { get; set; }
        public Nullable<int> Id_Paciente { get; set; }
        public string Cedula { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
