//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
        public Medicamento()
        {
            this.Paciente_Medicamento = new HashSet<Paciente_Medicamento>();
        }
    
        public int Id_Medicamento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Casa_Farmaceutica { get; set; }
    
        public virtual ICollection<Paciente_Medicamento> Paciente_Medicamento { get; set; }
    }
}
