//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
        public Medicamento()
        {
            this.PacienteMedicamentoes = new HashSet<PacienteMedicamento>();
        }
    
        public int idMedicamento { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string casaFarmaceutica { get; set; }
    
        public virtual ICollection<PacienteMedicamento> PacienteMedicamentoes { get; set; }
    }
}
