//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoTECEntities : DbContext
    {
        public CoTECEntities()
            : base("name=CoTECEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Centro_Hospitalario> Centro_Hospitalario { get; set; }
        public DbSet<Contacto> Contactoes { get; set; }
        public DbSet<Medicamento> Medicamentoes { get; set; }
        public DbSet<Medida_Sanitaria> Medida_Sanitaria { get; set; }
        public DbSet<Paciente> Pacientes { get; set; }
        public DbSet<Paciente_Medicamento> Paciente_Medicamento { get; set; }
        public DbSet<Patologia> Patologias { get; set; }
        public DbSet<Persona> Personas { get; set; }
        public DbSet<Persona_Patologia> Persona_Patologia { get; set; }
        public DbSet<Ubicacion> Ubicacions { get; set; }
        public DbSet<Ubicacion_Medida_Sanitaria> Ubicacion_Medida_Sanitaria { get; set; }
    }
}
