//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {

        public int idPaciente { get; set; }
        public string estado { get; set; }
        public string internado { get; set; }
        public string uci { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public int idCentroHospitalario { get; set; }
        public string cedula { get; set; }
    
    }
}
