//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Contactoes = new HashSet<Contacto>();
            this.PacienteMedicamentoes = new HashSet<PacienteMedicamento>();
        }
    
        public int idPaciente { get; set; }
        public string internado { get; set; }
        public string uci { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public int idEstadoPaciente { get; set; }
        public int idCentroHospitalario { get; set; }
        public string cedula { get; set; }
    
        public virtual CentroHospitalario CentroHospitalario { get; set; }
        public virtual ICollection<Contacto> Contactoes { get; set; }
        public virtual EstadoPaciente EstadoPaciente { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<PacienteMedicamento> PacienteMedicamentoes { get; set; }
    }
}
