//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente_Medicamento
    {
        public int Id_Paciente_Medicamento { get; set; }
        public int Id_Medicamento { get; set; }
        public int Id_Paciente { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
