//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Contactoes = new HashSet<Contacto>();
            this.Paciente_Medicamento = new HashSet<Paciente_Medicamento>();
        }
    
        public int Id_Paciente { get; set; }
        public string Estado { get; set; }
        public string Internado { get; set; }
        public string UCI { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public int Id_Centro_Hospitalario { get; set; }
        public string Cedula { get; set; }
    
        public virtual Centro_Hospitalario Centro_Hospitalario { get; set; }
        public virtual ICollection<Contacto> Contactoes { get; set; }
        public virtual ICollection<Paciente_Medicamento> Paciente_Medicamento { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
