//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patologia
    {
        public Patologia()
        {
            this.Persona_Patologia = new HashSet<Persona_Patologia>();
        }
    
        public int Id_Patologia { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Tratamiento { get; set; }
    
        public virtual ICollection<Persona_Patologia> Persona_Patologia { get; set; }
    }
}
