//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.CentroHospitalarios = new HashSet<CentroHospitalario>();
            this.Contactoes = new HashSet<Contacto>();
            this.Pacientes = new HashSet<Paciente>();
            this.PersonaPatologias = new HashSet<PersonaPatologia>();
        }
    
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string nacionalidad { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public int idUbicacion { get; set; }
    
        public virtual ICollection<CentroHospitalario> CentroHospitalarios { get; set; }
        public virtual ICollection<Contacto> Contactoes { get; set; }
        public virtual ICollection<Paciente> Pacientes { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual ICollection<PersonaPatologia> PersonaPatologias { get; set; }
    }
}
