//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona_Patologia
    {
        public int Id_Persona_Patologia { get; set; }
        public string Cedula { get; set; }
        public int Id_Patologia { get; set; }
    
        public virtual Patologia Patologia { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
