//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Contactoes = new HashSet<Contacto>();
            this.Pacientes = new HashSet<Paciente>();
            this.Persona_Patologia = new HashSet<Persona_Patologia>();
        }
    
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public int Id_Ubicacion { get; set; }
    
        public virtual ICollection<Contacto> Contactoes { get; set; }
        public virtual ICollection<Paciente> Pacientes { get; set; }
        public virtual ICollection<Persona_Patologia> Persona_Patologia { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
