//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public Ubicacion()
        {
            this.Centro_Hospitalario = new HashSet<Centro_Hospitalario>();
            this.Personas = new HashSet<Persona>();
            this.Ubicacion_Medida_Sanitaria = new HashSet<Ubicacion_Medida_Sanitaria>();
        }
    
        public int Id_Ubicacion { get; set; }
        public string Continente { get; set; }
        public string Pais { get; set; }
        public string Region { get; set; }
    
        public virtual ICollection<Centro_Hospitalario> Centro_Hospitalario { get; set; }
        public virtual ICollection<Persona> Personas { get; set; }
        public virtual ICollection<Ubicacion_Medida_Sanitaria> Ubicacion_Medida_Sanitaria { get; set; }
    }
}
