//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion_Medida_Sanitaria
    {
        public int Id_Ubicacion_Medida_Sanitaria { get; set; }
        public int Id_Ubicacion { get; set; }
        public int Id_Medida_Sanitaria { get; set; }
    
        public virtual Medida_Sanitaria Medida_Sanitaria { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
